version: "0.2"
ignorePaths:
  - "**/*.egg-info/**"
  - "local/__pycache__/**"
dictionaryDefinitions:
  - name: french
    path: cspell.fr_fr.txt
    addWords: true
dictionaries:
  - python
  - french
words: []
ignoreWords:
  - toutsurmoneau
  - signin
  - ZSESSID
  - JJMMYYY
  - tsme
  - domoticz
  - ooii
import: []
enableFiletypes:
  - shellscript
ignoreRegExpList:
  - Email
  - >-
    /ftp:[^\s]*/g
patterns:
  - name: markdown_code_block
    pattern: |
      /
          ^(\s*`{3,}).*     # match the ```
          [\s\S]*?          # the block of code
          ^\1               # end of the block
      /gmx
languageSettings:
  - languageId: markdown
    ignoreRegExpList:
      - markdown_code_block
